source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.12'

target 'WebViewScreenSaver' do
    pod 'AFNetworking', '~> 3.0'
end

target'WebViewScreenSaverRig' do
    pod 'AFNetworking', '~> 3.0'
end
